"""
jellyfin_config.py — Mimir Jellyfin Portable Configuration Writer

Writes initial Jellyfin XML config files to the data directory before the
Jellyfin process is started. This is intentionally run every time — it only
writes files that don't already exist, so it's safe to call on every launch.

Files written:
  {jellyfin_data}/config/network.xml   — port, HTTPS off, UPnP/AutoDiscovery off
  {jellyfin_data}/config/system.xml    — cache/metadata/transcode paths, log retention

These complement the --datadir and --cachedir flags passed to jellyfin.exe in
service_manager.py. Together they ensure Jellyfin's data stays entirely on the
drive regardless of which machine it's plugged into.

Note on first-run wizard:
  Jellyfin will still show its browser-based setup wizard on the very first
  run (IsStartupWizardCompleted is false until the user completes it). That's
  expected — the user creates their admin account through the embedded web view.
  After that first-run wizard, Jellyfin is fully configured and will skip it
  on subsequent launches.
"""

from pathlib import Path


def write_jellyfin_config(jellyfin_data: Path, jellyfin_port: int = 8096) -> bool:
    """
    Write portable Jellyfin config files to {jellyfin_data}/config/.

    Only writes files that don't exist yet — safe to call every launch.
    Returns True if all files were in place (written or pre-existing), False on error.
    """
    config_dir = jellyfin_data / "config"
    try:
        config_dir.mkdir(parents=True, exist_ok=True)
    except OSError:
        return False

    success = True
    success &= _write_network_xml(config_dir, jellyfin_port)
    success &= _write_system_xml(jellyfin_data, config_dir)
    return success


# --------------------------------------------------------- network.xml

_NETWORK_XML = """\
<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- Mimir portable config — generated by jellyfin_config.py -->
  <!-- Only edit this file if you know what you're doing; it will not be regenerated if it exists. -->

  <!-- HTTP port for the Jellyfin web interface and API -->
  <HttpServerPortNumber>{port}</HttpServerPortNumber>
  <PublicPort>{port}</PublicPort>

  <!-- HTTPS disabled — Mimir runs fully local, no TLS needed -->
  <HttpsPortNumber>8920</HttpsPortNumber>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <CertificatePath />
  <CertificatePassword />

  <!-- Local-only operation — no UPnP or network discovery -->
  <EnableUPnP>false</EnableUPnP>
  <AutoDiscovery>false</AutoDiscovery>
  <AutoDiscoveryTracing>false</AutoDiscoveryTracing>

  <!-- IPv6 not needed for local use -->
  <EnableIPv6>false</EnableIPv6>
  <EnableIPv4>true</EnableIPv4>

  <!-- Network binding: localhost only.
       Jellyfin has no socket-level bind-address CLI flag. The combination of
       EnableRemoteAccess=false and LocalNetworkAddresses=127.0.0.1 is the
       Jellyfin-recommended approach for local-only operation. Ollama uses the
       OLLAMA_HOST=127.0.0.1 env var for its socket binding (see service_manager.py). -->
  <LocalNetworkAddresses>
    <string>127.0.0.1</string>
  </LocalNetworkAddresses>
  <LocalNetworkSubnets />

  <!-- Remote access hard-disabled — Mimir is offline personal use only -->
  <EnableRemoteAccess>false</EnableRemoteAccess>
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
</NetworkConfiguration>
"""


def _write_network_xml(config_dir: Path, port: int) -> bool:
    target = config_dir / "network.xml"
    if target.exists():
        return True  # Don't overwrite existing user config
    try:
        target.write_text(
            _NETWORK_XML.format(port=port),
            encoding="utf-8"
        )
        return True
    except OSError:
        return False


# --------------------------------------------------------- system.xml

_SYSTEM_XML = """\
<?xml version="1.0" encoding="utf-8"?>
<ServerConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- Mimir portable config — generated by jellyfin_config.py -->
  <!-- Only edit this file if you know what you're doing; it will not be regenerated if it exists. -->

  <!-- First-run wizard: set to false so Jellyfin shows the setup wizard -->
  <!-- Jellyfin sets this to true automatically after wizard completion -->
  <IsStartupWizardCompleted>false</IsStartupWizardCompleted>

  <!-- Log retention — 3 days is plenty for a personal portable system -->
  <LogFileRetentionDays>3</LogFileRetentionDays>

  <!-- Drive-relative data paths — all stay on the SSD -->
  <CachePath>{cache_path}</CachePath>
  <MetadataPath>{metadata_path}</MetadataPath>
  <TranscodingTempPath>{transcode_path}</TranscodingTempPath>

  <!-- Disable network discovery at server level too -->
  <AutoDiscovery>false</AutoDiscovery>
  <EnableUPnP>false</EnableUPnP>

  <!-- Don't auto-open browser on startup — Mimir handles that -->
  <AutoRunWebApp>false</AutoRunWebApp>

  <!-- Metadata and image settings -->
  <SaveMetadataHidden>false</SaveMetadataHidden>
  <ImageExtractionTimeoutMs>0</ImageExtractionTimeoutMs>
  <EnableFolderView>false</EnableFolderView>
  <EnableGroupingIntoCollections>true</EnableGroupingIntoCollections>
  <DisplaySpecialsWithinSeasons>true</DisplaySpecialsWithinSeasons>

  <!-- Minimal plugin loading — no external calls -->
  <PluginRepositories />

  <!-- Transcoding: hardware acceleration attempt if available, software fallback -->
  <EnableManagedTranscoding>true</EnableManagedTranscoding>
  <HardwareAccelerationType>auto</HardwareAccelerationType>

  <!-- Path substitutions: none by default -->
  <PathSubstitutions />
</ServerConfiguration>
"""


def _write_system_xml(jellyfin_data: Path, config_dir: Path) -> bool:
    target = config_dir / "system.xml"
    if target.exists():
        return True  # Don't overwrite existing user config

    # Build drive-relative paths (use forward slashes — Jellyfin handles both)
    cache_path = str(jellyfin_data / "cache").replace("\\", "/")
    metadata_path = str(jellyfin_data / "metadata").replace("\\", "/")
    transcode_path = str(jellyfin_data / "transcodes").replace("\\", "/")

    try:
        target.write_text(
            _SYSTEM_XML.format(
                cache_path=cache_path,
                metadata_path=metadata_path,
                transcode_path=transcode_path,
            ),
            encoding="utf-8"
        )
        return True
    except OSError:
        return False


# --------------------------------------------------------- logging.json

_LOGGING_JSON = """\
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Warning",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning",
        "Emby": "Warning",
        "Jellyfin": "Warning",
        "MediaBrowser": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "{log_path}",
          "rollingInterval": "Day",
          "retainedFileCountLimit": 3,
          "outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] {Message:lj}{NewLine}{Exception}"
        }
      }
    ]
  }
}
"""


def write_logging_config(jellyfin_data: Path) -> bool:
    """
    Write a minimal logging config that keeps logs in {jellyfin_data}/log/
    and retains only 3 days' worth.
    """
    config_dir = jellyfin_data / "config"
    target = config_dir / "logging.json"
    if target.exists():
        return True

    log_path = str(jellyfin_data / "log" / "jellyfin-.log").replace("\\", "/")
    try:
        config_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(
            _LOGGING_JSON.format(log_path=log_path),
            encoding="utf-8"
        )
        return True
    except OSError:
        return False


def prepare_jellyfin_data_dirs(jellyfin_data: Path) -> None:
    """
    Ensure all subdirectories Jellyfin needs exist before it starts.
    Jellyfin creates these itself on first run, but creating them upfront
    avoids any race conditions on very fast launches.
    """
    subdirs = ["config", "cache", "metadata", "transcodes", "log", "data", "plugins"]
    for subdir in subdirs:
        (jellyfin_data / subdir).mkdir(parents=True, exist_ok=True)
